In [3]:
import numpy as np
import pandas as pd

In [5]:
dataset=pd.read_csv(r"C:\Users\admin\Downloads\BlackFridayfinal.csv")

In [6]:
dataset

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
5       1000003  P00193542      M  26-35          15             A   
6       1000004  P00184942      M  46-50           7             B   
7       1000004  P00346142      M  46-50           7             B   
8       1000004   P0097242      M  46-50           7             B   
9       1000005  P00274942      M  26-35          20             A   
10      1000005  P00251242      M  26-35          20             A   
11      1000005  P00014542      M  26-35          20             A   
12      1000005  P00031342      M  26-35          20             A   
13      1000005  P00145042      M  26-35          20             A   
14      1000006  P00231342      F  51-55           9             A   
15      1000006  P00190242      F  51-55           9             A   
16      1000006   P0096642      F  51-55           9             A   
17      1000006  P00058442      F  51-55           9             A   
18      1000007  P00036842      M  36-45           1             B   
19      1000008  P00249542      M  26-35          12             C   
20      1000008  P00220442      M  26-35          12             C   
21      1000008  P00156442      M  26-35          12             C   
22      1000008  P00213742      M  26-35          12             C   
23      1000008  P00214442      M  26-35          12             C   
24      1000008  P00303442      M  26-35          12             C   
25      1000009  P00135742      M  26-35          17             C   
26      1000009  P00039942      M  26-35          17             C   
27      1000009  P00161442      M  26-35          17             C   
28      1000009  P00078742      M  26-35          17             C   
29      1000010  P00085942      F  36-45           1             B   
...         ...        ...    ...    ...         ...           ...   
537547  1004733  P00244042      M  18-25          18             C   
537548  1004734  P00111042      M  51-55           1             B   
537549  1004734  P00345842      M  51-55           1             B   
537550  1004735  P00278242      M  46-50           3             C   
537551  1004735  P00313442      M  46-50           3             C   
537552  1004735   P0098642      M  46-50           3             C   
537553  1004735  P00119342      M  46-50           3             C   
537554  1004735  P00114042      M  46-50           3             C   
537555  1004735  P00135142      M  46-50           3             C   
537556  1004736  P00194542      M  18-25          20             A   
537557  1004736  P00175242      M  18-25          20             A   
537558  1004736  P00101942      M  18-25          20             A   
537559  1004736  P00109142      M  18-25          20             A   
537560  1004736  P00084842      M  18-25          20             A   
537561  1004736  P00078142      M  18-25          20             A   
537562  1004736  P00146742      M  18-25          20             A   
537563  1004736  P00154642      M  18-25          20             A   
537564  1004736  P00117442      M  18-25          20             A   
537565  1004736  P00051142      M  18-25          20             A   
537566  1004736  P00048742      M  18-25          20             A   
537567  1004736  P00157542      M  18-25          20             A   
537568  1004736  P00250642      M  18-25          20             A   
537569  1004736  P00023142      M  18-25          20             A   
537570  1004736  P00162442      M  18-25          20             A   
537571  1004737  P00221442      M  36-45          16             C   
537572  1004737  P

In [7]:
dataset.isnull().any()

User_ID                       False
Product_ID                    False
Gender                        False
Age                           False
Occupation                    False
City_Category                 False
Stay_In_Current_City_Years    False
Marital_Status                False
Product_Category_1            False
Product_Category_2             True
Product_Category_3             True
Purchase                      False
dtype: bool

In [8]:
dataset['Product_Category_2'].mode()[0]

8.0

In [9]:
 dataset['Product_Category_2'].fillna(dataset['Product_Category_2'].mode()[0],inplace=True)

In [10]:
dataset

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
5       1000003  P00193542      M  26-35          15             A   
6       1000004  P00184942      M  46-50           7             B   
7       1000004  P00346142      M  46-50           7             B   
8       1000004   P0097242      M  46-50           7             B   
9       1000005  P00274942      M  26-35          20             A   
10      1000005  P00251242      M  26-35          20             A   
11      1000005  P00014542      M  26-35          20             A   
12      1000005  P00031342      M  26-35          20             A   
13      1000005  P00145042      M  26-35          20             A   
14      1000006  P00231342      F  51-55           9             A   
15      1000006  P00190242      F  51-55           9             A   
16      1000006   P0096642      F  51-55           9             A   
17      1000006  P00058442      F  51-55           9             A   
18      1000007  P00036842      M  36-45           1             B   
19      1000008  P00249542      M  26-35          12             C   
20      1000008  P00220442      M  26-35          12             C   
21      1000008  P00156442      M  26-35          12             C   
22      1000008  P00213742      M  26-35          12             C   
23      1000008  P00214442      M  26-35          12             C   
24      1000008  P00303442      M  26-35          12             C   
25      1000009  P00135742      M  26-35          17             C   
26      1000009  P00039942      M  26-35          17             C   
27      1000009  P00161442      M  26-35          17             C   
28      1000009  P00078742      M  26-35          17             C   
29      1000010  P00085942      F  36-45           1             B   
...         ...        ...    ...    ...         ...           ...   
537547  1004733  P00244042      M  18-25          18             C   
537548  1004734  P00111042      M  51-55           1             B   
537549  1004734  P00345842      M  51-55           1             B   
537550  1004735  P00278242      M  46-50           3             C   
537551  1004735  P00313442      M  46-50           3             C   
537552  1004735   P0098642      M  46-50           3             C   
537553  1004735  P00119342      M  46-50           3             C   
537554  1004735  P00114042      M  46-50           3             C   
537555  1004735  P00135142      M  46-50           3             C   
537556  1004736  P00194542      M  18-25          20             A   
537557  1004736  P00175242      M  18-25          20             A   
537558  1004736  P00101942      M  18-25          20             A   
537559  1004736  P00109142      M  18-25          20             A   
537560  1004736  P00084842      M  18-25          20             A   
537561  1004736  P00078142      M  18-25          20             A   
537562  1004736  P00146742      M  18-25          20             A   
537563  1004736  P00154642      M  18-25          20             A   
537564  1004736  P00117442      M  18-25          20             A   
537565  1004736  P00051142      M  18-25          20             A   
537566  1004736  P00048742      M  18-25          20             A   
537567  1004736  P00157542      M  18-25          20             A   
537568  1004736  P00250642      M  18-25          20             A   
537569  1004736  P00023142      M  18-25          20             A   
537570  1004736  P00162442      M  18-25          20             A   
537571  1004737  P00221442      M  36-45          16             C   
537572  1004737  P

In [11]:
 dataset['Product_Category_3'].fillna(dataset['Product_Category_3'].mode()[0],inplace=True)

In [12]:
dataset

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
5       1000003  P00193542      M  26-35          15             A   
6       1000004  P00184942      M  46-50           7             B   
7       1000004  P00346142      M  46-50           7             B   
8       1000004   P0097242      M  46-50           7             B   
9       1000005  P00274942      M  26-35          20             A   
10      1000005  P00251242      M  26-35          20             A   
11      1000005  P00014542      M  26-35          20             A   
12      1000005  P00031342      M  26-35          20             A   
13      1000005  P00145042      M  26-35          20             A   
14      1000006  P00231342      F  51-55           9             A   
15      1000006  P00190242      F  51-55           9             A   
16      1000006   P0096642      F  51-55           9             A   
17      1000006  P00058442      F  51-55           9             A   
18      1000007  P00036842      M  36-45           1             B   
19      1000008  P00249542      M  26-35          12             C   
20      1000008  P00220442      M  26-35          12             C   
21      1000008  P00156442      M  26-35          12             C   
22      1000008  P00213742      M  26-35          12             C   
23      1000008  P00214442      M  26-35          12             C   
24      1000008  P00303442      M  26-35          12             C   
25      1000009  P00135742      M  26-35          17             C   
26      1000009  P00039942      M  26-35          17             C   
27      1000009  P00161442      M  26-35          17             C   
28      1000009  P00078742      M  26-35          17             C   
29      1000010  P00085942      F  36-45           1             B   
...         ...        ...    ...    ...         ...           ...   
537547  1004733  P00244042      M  18-25          18             C   
537548  1004734  P00111042      M  51-55           1             B   
537549  1004734  P00345842      M  51-55           1             B   
537550  1004735  P00278242      M  46-50           3             C   
537551  1004735  P00313442      M  46-50           3             C   
537552  1004735   P0098642      M  46-50           3             C   
537553  1004735  P00119342      M  46-50           3             C   
537554  1004735  P00114042      M  46-50           3             C   
537555  1004735  P00135142      M  46-50           3             C   
537556  1004736  P00194542      M  18-25          20             A   
537557  1004736  P00175242      M  18-25          20             A   
537558  1004736  P00101942      M  18-25          20             A   
537559  1004736  P00109142      M  18-25          20             A   
537560  1004736  P00084842      M  18-25          20             A   
537561  1004736  P00078142      M  18-25          20             A   
537562  1004736  P00146742      M  18-25          20             A   
537563  1004736  P00154642      M  18-25          20             A   
537564  1004736  P00117442      M  18-25          20             A   
537565  1004736  P00051142      M  18-25          20             A   
537566  1004736  P00048742      M  18-25          20             A   
537567  1004736  P00157542      M  18-25          20             A   
537568  1004736  P00250642      M  18-25          20             A   
537569  1004736  P00023142      M  18-25          20             A   
537570  1004736  P00162442      M  18-25          20             A   
537571  1004737  P00221442      M  36-45          16             C   
537572  1004737  P

In [13]:
#dataset.fillna(0, inplace=True)

In [14]:
#dataset

In [15]:
x=dataset.iloc[:,2:11].values

In [16]:
x

array([['F', '0-17', 10, ..., 3, 8.0, 16.0],
       ['F', '0-17', 10, ..., 1, 6.0, 14.0],
       ['F', '0-17', 10, ..., 12, 8.0, 16.0],
       ...,
       ['M', '36-45', 16, ..., 8, 15.0, 16.0],
       ['M', '36-45', 16, ..., 5, 8.0, 16.0],
       ['M', '36-45', 16, ..., 5, 8.0, 16.0]], dtype=object)

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le=LabelEncoder()

In [19]:
x[:,0]=le.fit_transform(x[:,0])

In [20]:
x

array([[0, '0-17', 10, ..., 3, 8.0, 16.0],
       [0, '0-17', 10, ..., 1, 6.0, 14.0],
       [0, '0-17', 10, ..., 12, 8.0, 16.0],
       ...,
       [1, '36-45', 16, ..., 8, 15.0, 16.0],
       [1, '36-45', 16, ..., 5, 8.0, 16.0],
       [1, '36-45', 16, ..., 5, 8.0, 16.0]], dtype=object)

In [21]:
x[:,1]=le.fit_transform(x[:,1])

In [22]:
x

array([[0, 0, 10, ..., 3, 8.0, 16.0],
       [0, 0, 10, ..., 1, 6.0, 14.0],
       [0, 0, 10, ..., 12, 8.0, 16.0],
       ...,
       [1, 3, 16, ..., 8, 15.0, 16.0],
       [1, 3, 16, ..., 5, 8.0, 16.0],
       [1, 3, 16, ..., 5, 8.0, 16.0]], dtype=object)

In [23]:
x[:,3]=le.fit_transform(x[:,3])

In [24]:
x

array([[0, 0, 10, ..., 3, 8.0, 16.0],
       [0, 0, 10, ..., 1, 6.0, 14.0],
       [0, 0, 10, ..., 12, 8.0, 16.0],
       ...,
       [1, 3, 16, ..., 8, 15.0, 16.0],
       [1, 3, 16, ..., 5, 8.0, 16.0],
       [1, 3, 16, ..., 5, 8.0, 16.0]], dtype=object)

In [25]:
x[4]

array([1, 6, 16, 2, 4, 0, 8, 8.0, 16.0], dtype=object)

In [26]:
x[12]

array([1, 2, 20, 0, 1, 1, 8, 8.0, 16.0], dtype=object)

In [27]:
 from sklearn.preprocessing import OneHotEncoder

In [28]:
oh= OneHotEncoder()

In [29]:
oh=OneHotEncoder(categorical_features=[1])
x=oh.fit_transform(x).toarray()

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\admin\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [30]:
x = x[:,1:]

In [31]:
x

array([[ 0.,  0.,  0., ...,  3.,  8., 16.],
       [ 0.,  0.,  0., ...,  1.,  6., 14.],
       [ 0.,  0.,  0., ..., 12.,  8., 16.],
       ...,
       [ 0.,  0.,  1., ...,  8., 15., 16.],
       [ 0.,  0.,  1., ...,  5.,  8., 16.],
       [ 0.,  0.,  1., ...,  5.,  8., 16.]])

In [32]:
oh=OneHotEncoder(categorical_features=[3])
x=oh.fit_transform(x).toarray()

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\admin\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [33]:
x = x[:,1:]

In [34]:
x

array([[ 0.,  0.,  0., ...,  3.,  8., 16.],
       [ 0.,  0.,  0., ...,  1.,  6., 14.],
       [ 0.,  0.,  0., ..., 12.,  8., 16.],
       ...,
       [ 0.,  0.,  0., ...,  8., 15., 16.],
       [ 0.,  0.,  0., ...,  5.,  8., 16.],
       [ 0.,  0.,  0., ...,  5.,  8., 16.]])

In [35]:
x[0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  0.,  2.,  0.,  3.,  8.,
       16.])

In [36]:
x[1]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  0.,  2.,  0.,  1.,  6.,
       14.])

In [40]:
x[537547]

array([ 0.,  1.,  0.,  0.,  0.,  0.,  1., 18.,  2.,  1.,  0.,  1.,  2.,
       15.])

In [39]:
x[29]

array([0., 0., 0., 1., 0., 0., 0., 1., 1., 4., 1., 2., 4., 8.])

In [31]:
x.shape

(537577, 14)

In [32]:
y=dataset.iloc[:,11:12].values

In [33]:
y

array([[ 8370],
       [15200],
       [ 1422],
       ...,
       [ 8043],
       [ 7172],
       [ 6875]], dtype=int64)

In [34]:
y.shape

(537577, 1)

In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [36]:
import tensorflow

In [37]:
import keras

Using TensorFlow backend.


In [38]:
from keras.models import Sequential
from keras.layers import Dense

In [39]:
model=Sequential()

In [40]:
model.add(Dense(input_dim=14,init="random_uniform",output_dim=20))

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=14, units=20, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


Instructions for updating:
Colocations handled automatically by placer.


In [41]:
model.add(Dense(init="random_uniform",output_dim=25))

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=25, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [42]:
model.add(Dense(init="random_uniform",output_dim=1))

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [43]:
model.compile(optimizer='adam',loss="mean_squared_error",metrics=['mse'])

In [44]:
model.fit(X_train,y_train,epochs=50,batch_size=64)

Instructions for updating:
Use tf.cast instead.
Epoch 1/50
430061/430061 [==============================] - ETA: 0s - loss: 30215229.7827 - mean_squared_error: 30215229.7827 ETA: 0s - loss: 30426031.5887 - mean_squared_error: 30426 - 6s 13us/step - loss: 30188005.2486 - mean_squared_error: 30188005.2486
Epoch 2/50
430061/430061 [==============================] - 4s 10us/step - loss: 23920792.9929 - mean_squared_error: 23920792.9929
Epoch 3/50
430061/430061 [==============================] - 5s 11us/step - loss: 22697238.8875 - mean_squared_error: 22697238.8875
Epoch 4/50
430061/430061 [==============================] - 6s 13us/step - loss: 22294746.5940 - mean_squared_error: 22294746.5940
Epoch 5/50
430061/430061 [==============================] - 5s 11us/step - loss: 22229167.9453 - mean_squared_error: 22229167.9453
Epoch 6/50
430061/430061 [==============================] - 4s 10us/step - loss: 22183486.2106 - mean_squared_error: 22183486.2106
Epoch 7/50
430061/430061 [==============

In [45]:
y_pred=model.predict(X_test)

In [46]:
y_pred

array([[10866.5   ],
       [ 8495.658 ],
       [ 9410.035 ],
       ...,
       [ 7857.2363],
       [ 9566.528 ],
       [ 9579.729 ]], dtype=float32)

In [47]:
y_pred=(y_pred>0.5)

In [48]:
y_pred

array([[ True],
       [ True],
       [ True],
       ...,
       [ True],
       [ True],
       [ True]])

In [49]:
from sklearn.metrics import mean_squared_error

In [50]:
test=mean_squared_error(y_pred,y_test) 

In [51]:
test

111545240.14275084

In [52]:
from sklearn.metrics import confusion_matrix

In [53]:
confusion_matrix(y_pred,y_test)

array([[0, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [54]:
y_pred_single=model.predict(np.array([[0,0,0,0,0,0,0,0,10,2,0,3,8.0,16.0]]))

In [55]:
y_pred_single

array([[12449.65]], dtype=float32)

In [59]:
y_pred_single=model.predict(np.array([[0,0,0,0,0,1,1,16,2,4,0,8,8,16]]))

In [60]:
y_pred_single

array([[9222.963]], dtype=float32)

In [62]:
y_pred_single=model.predict(np.array([[ 0.,  0.,  1.,  0.,  0.,  0.,  1., 20.,  0.,  1.,  1.,  8.,  8.,
       16.]]))

In [63]:
y_pred_single

array([[8104.987]], dtype=float32)